/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sapient.casestudy.ecommerce.main;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import com.sapient.casestudy.ecommerce.model.Product;
import com.sapient.casestudy.ecommerce.service.ProductService;

@EntityScan("com.sapient.casestudy.ecommerce.model")
@EnableJpaRepositories("com.sapient.casestudy.ecommerce.repository")
@ComponentScan(basePackages = { "com.sapient.casestudy.ecommerce"})
@SpringBootApplication
public class ECommerceApplication {

    public static void main(String[] args) {
        SpringApplication.run(ECommerceApplication.class, args);
    }
    
    @Bean
    CommandLineRunner runner(ProductService productService) {
        return args -> {
            productService.save(new Product("1", "Hugo Boss", "Mens Apparel,Shirts", "HG001", "HG Camp shirt", "", 999.0, 36, "White"));
            productService.save(new Product("2", "Ralph Lauren", "Mens Apparel,Shirts", "RL001", "Epaulette shirt", "", 1500.0, 32, "Black"));
            productService.save(new Product("3", "Michael Kors", "Mens Apparel,Shirts", "MK001", "Flannel shirt", "", 1999.0, 36, "Brown"));
            productService.save(new Product("4", "Guess", "Mens Apparel,Shirts", "GS001", "Baseball shirt", "", 1399.0, 36, "White"));
            productService.save(new Product("5", "Diesel", "Mens Apparel,Shirts", "DS001", "Epaulette shirt", "", 2499.0, 36, "Dark Blue"));
            productService.save(new Product("6", "Aeropostale", "Mens Apparel,Shirts", "AP001", "Flannel shirt", "", 1289.0, 36, "purple"));
            productService.save(new Product("7", "Lacoste", "Mens Apparel,Shirts", "LC001", "Casual shirt", "", 3214.0, 36, "Maroon"));
            productService.save(new Product("8", "Calvin Klein", "Mens Apparel,Shirts", "CK001", "Granddad shirt", "", 5054.0, 36, "Peach"));
            productService.save(new Product("9", "Nautica", "Mens Apparel,Shirts", "NT001", "Henley shirt", "", 2365.0, 36, "Sky Blue"));
            productService.save(new Product("10", "Lucky", "Mens Apparel,Shirts", "LK001", "Formal shirt", "", 2311.0, 36, "Yellow"));
            productService.save(new Product("10", "Puma", "Mens Apparel,Shirts", "PM01", "T-Shirt", "", 1999.0, 36, "Green"));
            productService.save(new Product("10", "Nike", "Mens Apparel,Shirts", "NK001", "Sweatshirt", "", 2999.0, 36, "Black"));
            productService.save(new Product("10", "Adidas", "Mens Apparel,Shirts", "AD001", "Jersey shirt", "", 5999.0, 36, "Black"));
            productService.save(new Product("11", "Calvin Klein", "Mens Apparel,Shirts", "CK002", "GrandHyat Shirt", "", 6024.0, 36, "Violet")); 
        };
    }

}
